<?php
include('header.php');
?>

<?php


 $num = $_POST['email'];
 $senha = $_POST['senha'];

$inserir = "SELECT * FROM cadastro WHERE numero='$num' AND senha='$senha'";
$feito = $conexao -> query($inserir);

   if (mysqli_num_rows($feito) > 0) {
    $dad = mysqli_fetch_array($feito);
       
    session_start();
    $_SESSION['nome'] = $dad['nome'];
    $_SESSION['num_est'] = $dad['numero'];
    $_SESSION['id'] = $dad['id'];
    $_SESSION['quando'] = $dad['quando'];
    $_SESSION['email'] = $dad['email'];
    $_SESSION['telefone'] = $dad['telefone'];
    $_SESSION['ano'] = $dad['ano'];
    $_SESSION['curso'] = $dad['curso'];
    $_SESSION['sala'] = $dad['sala'];
    $_SESSION['hab'] = $dad['habilidades'];
    header('location:dashboard.php');
}

else{
?>



<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Login | Garimpo </title>
    <script src="jquery.js"></script>
    <script src="jquery.min.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="estilo.css">
    <script src="bootstrap/js/bootstrap.js"></script>
    <link rel="stylesheet" href="bootstrap/css/bootstrap.css">
</head>
<body>
    <nav class="navbar navbar-light"  style="background: #047a04;"> 
        <div class="container"> 
            <a class="navbar-brand text-white" href="index.html"> 
               Garimpo
            </a> 
            <a class="text-white" href="tel:+244946445629">&phone; Ajuda</a>
        </div>
    </nav>
<br>
<center>
  <br>
  <div class="w-50" >
    <h2 class="text-success">Garimpo ISPT</h2>
    <hr></div>
  <br>
  <div style="width: 5rem; height: 5rem; display: grid; place-content: center;" class="mx-auto bg-danger">
    <!-- Generated by IcoMoon.io -->
<svg fill="white" class="rounded-3" version="1.1" xmlns="http://www.w3.org/2000/svg" width="54" height="54" viewBox="0 0 24 24">
<title>erro</title>
<path d="M16.316 6.624l-4.114 4.114-4.114-4.114-1.061 1.061 4.114 4.114-4.114 4.114 1.061 1.061 4.114-4.114 4.114 4.114 1.061-1.061-4.114-4.114 4.114-4.114-1.061-1.061z"></path>
<path d="M19.955 4.045c-2.036-2.036-4.848-3.295-7.955-3.295-6.213 0-11.25 5.037-11.25 11.25 0 3.107 1.259 5.919 3.295 7.955v0c2.036 2.036 4.848 3.295 7.955 3.295 6.213 0 11.25-5.037 11.25-11.25 0-3.107-1.259-5.919-3.295-7.955v0zM12 21.75c-5.376 0-9.75-4.374-9.75-9.75s4.374-9.75 9.75-9.75 9.75 4.374 9.75 9.75-4.374 9.75-9.75 9.75z"></path>
</svg>

  </div>
  <br>
  <h2>Não há nenhuma conta cadastrada com estes dados </h2><br>
  <p><a href="login.html">Clique aqui</a> para tentar novamente</p>
  <p>Ou <a href="cadastro.html">crie uma conta agora</a> </p>
</center>

<?php }?>

</body>
</html>